### PR TITLE
Enable strict and warnings on all tests

### PR DESCRIPTION
**Pull request by atoomic**
tested with #7 
you can view results from https://github.com/atoomic/mime-base64/actions/runs/138957956

### CODE REVIEW

**Comment by atoomic** [comment]
Hi @gisle I would appreciate any feedbacks from you.
Let me know if I can help.
thanks

**Comment by toddr** [comment]
@genio has taken maintenance of this module from gsile and is working on a release now.

**Comment by atoomic** [comment]
@genio ping

**Comment by genio** [comment]
@atoomic This is the first PR I'll pull in. I plan on getting to this later this evening: https://github.com/Dual-Life/mime-base64 is the new location

**Comment by genio** [comment]
Merged in https://github.com/Dual-Life/mime-base64/commit/d4e3a1fc5445b1ca8c08948ef37d0ed0075c75ba  this can be closed.  Thank you, @atoomic !!

**Comment by atoomic** [comment]
Thanks closing this case

**Pull request closed without merging**
